CREATE DATABASE IF NOT EXISTS stomach_overflow;
CREATE USER IF NOT EXISTS 'cook'@'localhost' IDENTIFIED BY 'securepass';
GRANT ALL ON stomach_overflow.* TO 'cook'@'localhost';
use stomach_overflow;
CREATE TABLE IF NOT EXISTS users (
id integer PRIMARY KEY NOT NULL AUTO_INCREMENT,
login varchar(30) NOT NULL UNIQUE,
password text NOT NULL,
full_name varchar(30) NOT NULL,
email_address varchar(255) NOT NULL UNIQUE,
profile_picture text NOT NULL,
rating integer NOT NULL DEFAULT 0,
role ENUM("admin", "user") NOT NULL DEFAULT "user",
notifications_on boolean NOT NULL DEFAULT 1,
email_confirmed boolean NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS posts (
id integer PRIMARY KEY NOT NULL AUTO_INCREMENT,
title text NOT NULL,
publish_date timestamp NOT NULL DEFAULT current_timestamp,
status ENUM("active", "inactive") NOT NULL DEFAULT "active",
content text NOT NULL,
author_id integer,
attachment text,
FOREIGN KEY (author_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS categories (
id integer PRIMARY KEY NOT NULL AUTO_INCREMENT,
title text NOT NULL,
description text
);
CREATE TABLE IF NOT EXISTS posts_categories (
post_id integer NOT NULL,
category_id integer NOT NULL,
FOREIGN KEY (post_id) REFERENCES posts(id),
FOREIGN KEY (category_id) REFERENCES categories(id)
);
CREATE TABLE IF NOT EXISTS preferences (
user_id integer NOT NULL,
category_id integer NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (category_id) REFERENCES categories(id)
);
CREATE TABLE IF NOT EXISTS favorites (
user_id integer NOT NULL,
post_id integer NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (post_id) REFERENCES posts(id)
);
CREATE TABLE IF NOT EXISTS followings (
user_id integer NOT NULL,
post_id integer NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (post_id) REFERENCES posts(id)
);
CREATE TABLE IF NOT EXISTS followers (
follower_id integer NOT NULL,
followed_id integer NOT NULL,
FOREIGN KEY (follower_id) REFERENCES users(id),
FOREIGN KEY (followed_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS comments (
id integer PRIMARY KEY NOT NULL AUTO_INCREMENT,
author_id integer,
publish_date timestamp NOT NULL DEFAULT current_timestamp,
content text NOT NULL,
post_id integer,
comment_id integer,
attachment text,
FOREIGN KEY (author_id) REFERENCES users(id),
FOREIGN KEY (post_id) REFERENCES posts(id),
FOREIGN KEY (comment_id) REFERENCES comments(id)
);
CREATE TABLE IF NOT EXISTS likes (
id integer PRIMARY KEY NOT NULL AUTO_INCREMENT,
author_id integer NOT NULL,
publish_date timestamp NOT NULL DEFAULT current_timestamp,
post_id integer,
comment_id integer,
type ENUM("like", "dislike") NOT NULL,
FOREIGN KEY (author_id) REFERENCES users(id),
FOREIGN KEY (post_id) REFERENCES posts(id),
FOREIGN KEY (comment_id) REFERENCES comments(id)
);
CREATE TABLE IF NOT EXISTS notifications (
id integer PRIMARY KEY NOT NULL AUTO_INCREMENT,
publish_date timestamp NOT NULL DEFAULT current_timestamp,
addressee_id integer NOT NULL,
figurant_id integer,
post_id integer,
comment_id integer,
sense ENUM("is following you!", "is following your post:", "published a post:", "commented on you:", "commented on the post you are following:", "locked the post:", "reacted to your post:", "reacted to your comment:") NOT NULL,
is_read boolean NOT NULL DEFAULT 0,
FOREIGN KEY (addressee_id) REFERENCES users(id),
FOREIGN KEY (figurant_id) REFERENCES users(id),
FOREIGN KEY (post_id) REFERENCES posts(id),
FOREIGN KEY (comment_id) REFERENCES comments(id)
);
INSERT INTO users (login, password, full_name, email_address, profile_picture, rating, role, email_confirmed) VALUES
("Kyouki_no_mad_scientist", "103b07211b2422e294012627a31b21428a34cd7f3b1537f7aaccb9e15b9a2ef7ca860c0b3809b7061cff7c1f11b91a74cb07658080cdafdd8255c8d78924da43", "Hououin Kyouma", "mail1@gmail.com", "../public/images/default_avatar.png", 19, "admin", 1),
("Tutturu", "103b07211b2422e294012627a31b21428a34cd7f3b1537f7aaccb9e15b9a2ef7ca860c0b3809b7061cff7c1f11b91a74cb07658080cdafdd8255c8d78924da43", "Mayushi☆", "mail2@gmail.com", "../public/images/default_avatar.png", 32, "user", 1),
("Superhacker_1905", "103b07211b2422e294012627a31b21428a34cd7f3b1537f7aaccb9e15b9a2ef7ca860c0b3809b7061cff7c1f11b91a74cb07658080cdafdd8255c8d78924da43", "Daru", "mail3@gmail.com", "../public/images/default_avatar.png", 14, "admin", 1),
("Kurigohan", "103b07211b2422e294012627a31b21428a34cd7f3b1537f7aaccb9e15b9a2ef7ca860c0b3809b7061cff7c1f11b91a74cb07658080cdafdd8255c8d78924da43", "Kurisu Makise", "mail4@gmail.com", "../public/images/default_avatar.png", 15, "user", 1),
("Shiny_finger", "103b07211b2422e294012627a31b21428a34cd7f3b1537f7aaccb9e15b9a2ef7ca860c0b3809b7061cff7c1f11b91a74cb07658080cdafdd8255c8d78924da43", "Moeka Kiryuu", "mail5@gmail.com", "../public/images/default_avatar.png", 8, "user", 1),
("Luka_Urushibara", "103b07211b2422e294012627a31b21428a34cd7f3b1537f7aaccb9e15b9a2ef7ca860c0b3809b7061cff7c1f11b91a74cb07658080cdafdd8255c8d78924da43", "Luka Urushibara", "mail6@gmail.com", "../public/images/default_avatar.png", 12, "user", 1),
("FarisNyanNyan", "103b07211b2422e294012627a31b21428a34cd7f3b1537f7aaccb9e15b9a2ef7ca860c0b3809b7061cff7c1f11b91a74cb07658080cdafdd8255c8d78924da43", "Faris NyanNyan", "mail7@gmail.com", "../public/images/default_avatar.png", 8, "user", 1),
("skyclad2010", "103b07211b2422e294012627a31b21428a34cd7f3b1537f7aaccb9e15b9a2ef7ca860c0b3809b7061cff7c1f11b91a74cb07658080cdafdd8255c8d78924da43", "Suzuha Amane", "mail8@gmail.com", "../public/images/default_avatar.png", 12, "user", 1);
INSERT INTO posts (title, status, content, author_id, attachment) VALUES
("What is Dr Pepper made of?", "active", "Good afternoon, ladies and gentlemen! I am going to make a great drink for true geniuses, that is, Dr Pepper. It may seem simple at first, but in reality even a genius like me has doubts about the ingredients. I have some assumptions about this, but I would also like to know your opinion.", (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), NULL),
("Espresso from instant coffee: is it real?", "inactive", "Good afternoon, ladies and gentlemen! Because I become sleepy and tired every day, I want to make some espresso. The problem is that I do not have any ground coffee, but I have instant one. Is it possible to make espresso from this, and if so, will that espresso give the same effect that one from ground coffee?", (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null),
("Why may sugar not caramelize?", "active", "Hello everyone! I want to cook my favorite crème caramel, but I have a terrible problem: when I try to make caramel, the sugar doesn't caramelize and becomes like on the picture. Would you tell me please what this may be connected with?", (SELECT id FROM users WHERE login = "Kurigohan"), "../public/images/1759755207973_photo_post.jpg"),
("Some interesting ideas about nuggets", "active", "Tutturu-♪ Mayushi wants to cook some nuggets, but there are no ideas what interesting things can be added to them... Can you please tell what unusual Mayushi can do with nuggets?", (SELECT id FROM users WHERE login = "Tutturu"), null),
("Is it possible to marinate bananas?", "active", "Tutturu-♪ Mayushi is a big fan of bananas and wans to try something interesting with them. The first idea that came to mide is to marinate them, but is it really possible? If so, is it a really good idea?", (SELECT id FROM users WHERE login = "Tutturu"), null),
("How to call popcorn in Coca-Cola syrup?", "active", "Hi guys! I got the idea to make popcorn in Coca-Cola syrup, and I'm wondering what this can be called. Is it pop-cola or coca-corn?", (SELECT id FROM users WHERE login = "Superhacker_1905"), null),
("About interesting cookies ideas", "active", "Hello everyone, can you please give me some interesting ideas on how I can make cookies? P.S. I have cooked taiyaki and shortbread, so you can also tell me how I can modify them.", (SELECT id FROM users WHERE login = "Luka_Urushibara"), null),
("Why may the foam on the coffee not stick?", "active", "Hi everyone! Lately, when I make coffee, the foam doesn't stay on top for some reason, even though I seem to heat the milk to the right temperature and froth it for the right ameownt of time. Can you suggest what else might be the problem?", (SELECT id FROM users WHERE login = "FarisNyanNyan"), null),
("Recipes from the past", "active", "Hi everyone! I'm fond of exploring the past, and I want to discover recipes that have a long history. Can you tell me about such recipes?", (SELECT id FROM users WHERE login = "skyclad2010"), null),
("What stock pot can I use for cooking cheese?", "active", "Hello everyone!❤️ I recently became intesested in making cheese! ( ☆∀☆) But I'm still unsure what kind of stock pot to use... Can you help me please? (。･´д`･。)", (SELECT id FROM users WHERE login = "Shiny_finger"), null);
INSERT INTO categories (title, description) VALUES
("Recipes", "A recipe is an instruction on how to prepare something. You can share your recipes and request them from other users."),
("Kitchenware", "Kitchenware refers to the tools, utensils, appliances, dishes, and cookware used in food preparation and the serving of food. Kitchenware can also be used to hold or store food before or after preparation."),
("Dairy products", "Dairy products or milk products are food products made from (or containing) milk. Dairy products include common grocery store food around the world such as yogurt, cheese, milk and butter."),
("Meat", "Meat is animal tissue, mostly muscle, that is eaten as food."),
("Eggs", "An egg is an organic vessel grown by an animal to carry a possibly fertilized egg cell. The most widely consumed eggs are those of fowl, especially chickens."),
("Vegetables", "Vegetables typically are savory or non-sweet produce (e.g. zucchini, lettuce, broccoli, and tomato). But some may be sweet-tasting (sweet potato)."),
("Fruits", "A fruit is the sweet- or not sweet- (even sour-) tasting produce of a specific plant (e.g., a peach, pear or lemon)."),
("Groats", "Groats are the hulled kernels of various cereal grains, such as oats, wheat, rye, and barley. Groats can also be produced from pseudocereal seeds such as buckwheat."),
("Pasta", "Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking. Pasta was originally only made with durum, although the definition has been expanded to include alternatives for a gluten-free diet, such as rice flour, or legumes such as beans or lentils."),
("Sweet", "Confections are items that are rich in sugar and carbohydrates, although exact definitions are difficult. In general, however, confections are divided into two broad and somewhat overlapping categories: baker's confections and sugar confections."),
("Sugar confections", "Sugar confections include sweet, sugar-based foods, which are usually eaten as snack food. This includes sugar candies, chocolates, candied fruits and nuts, chewing gum, and sometimes ice cream."),
("Cream", "Cream is a semi-finished confectionery finishing product used to decorate the surface of baked goods, layer and coat cake layers, and fill the cavities of baked goods. It is a lamellar, foamy mass made from egg whites or mélange, butter, cream, sour cream, granulated sugar, milk, and flavorings."),
("Pastry", "Pastry refers to a variety of doughs (often enriched with fat or eggs), as well as the sweet and savoury baked goods made from them. Sweetened pastries are often described as baker's confectionery."),
("Drinks", "A drink or beverage is a liquid intended for human consumption. In addition to their basic function of satisfying thirst, drinks play important roles in human culture."),
("Juice", "Juice is a drink made from the extraction or pressing of the natural liquid contained in fruit and vegetables. It is commonly consumed as a beverage or used as an ingredient or flavoring in foods or other beverages, such as smoothies."),
("Soft Drinks", "A soft drink is a class of drink containing no alcohol, usually (but not necessarily) carbonated, and typically including added sweetener. Coffee, tea, milk, cocoa, and unaltered fruit and vegetable juices are not considered soft drinks."),
("Hot drinks", "Hot drinks are those consumed heated. These include tea, coffee, cocoa, mate, mulled wine, sbiten, and various decoctions."),
("Tea", "Tea is an aromatic beverage prepared by pouring hot or boiling water over cured or fresh leaves, fruit, or other plant parts."),
("Coffee", "Coffee is a beverage brewed from roasted, ground coffee beans. There are also various coffee substitutes."),
("Alcoholic drinks", "An alcoholic beverage is any drink that contains alcohol. They are typically divided into three classes: beers, wines, and spirits; with alcohol content typically between 3% and 50%."),
("Soups", "Soup is a primarily liquid food, generally served warm or hot – though it is sometimes served chilled – made by cooking or otherwise combining meat or vegetables with stock, milk, or water."),
("Sauces", "In cooking, a sauce is a liquid, cream, or semi-solid food, served on or used in preparing other foods. Most sauces are not normally consumed by themselves; they add flavour, texture, and visual appeal to a dish."),
("Frying", "Frying is the cooking of food in oil or another fat."),
("Boiling", "Boiling is one of the most common types of thermal processing of food products by heating them in a boiling liquid (for example, water, milk, broth) or in an atmosphere of saturated steam."),
("Steaming", "Steaming is a method of cooking using steam. This is often done with a food steamer, a kitchen appliance made specifically to cook food with steam, but food can also be steamed in a wok."),
("Braising", "Braising is a combination-cooking method that uses both wet and dry heats: typically, the food is first browned at a high temperature, then simmered in a covered pot in cooking liquid (such as wine, broth, coconut milk or beer)."),
("Smoking", "Smoking is the process of flavoring, browning, cooking, or preserving food, particularly meat, fish and tea, by exposing it to smoke from burning or smoldering material, most often wood."),
("Baking", "Baking is a method of preparing food that uses dry heat, typically in an oven, but it can also be done in hot ashes, or on hot stones."),
("Fast food", "Fast food is a type of food served with reduced preparation and consumption time, simplified or eliminated cutlery, or served off the table."),
("Slavic", "Slavic cuisine is a collection of the different dishes and cooking traditions of the Slavic countries. Ingredients common to many Slavic dishes include groats, vegetables, mushrooms, berries, fish, game and poultry."),
("Caucasian", "Caucasian cuisine includes Georgian, Armenian, Azerbaijani and food of the North Caucasus. Common ingredients are meat, rice, dairy (especially fermented milk products and cheese), sour fruis, nuts and various seasonings (like red pepper, khmeli suneli, tarragon and other)."),
("French", "French cuisine is the cooking traditions and practices of France. Common ingredients are dairy, eggs, meat, vegetables, fruis, mushrooms, olive oil and various seasonings (like savory, marjoram, rosemary, thyme, oregano, and other)."),
("Italian", "Italian cuisine is a Mediterranean cuisine consisting of the ingredients, recipes, and cooking techniques developed in Italy since Roman times. Common ingregients are pasta, dairy, meat, vegetables, olive oil and various seasonings (like oregano, basil, rosemary, thyme, marjoram and other). There are also many coffee drinks."),
("Spanish", "Spanish cuisine consists of the traditions and practices of Spanish cooking. Common ingredients are meat, vegetables (especially potato), seafood and various seasonings."),
("Latin American", "Latin American cuisine is the typical foods, beverages, and cooking styles common to many of the countries and cultures in Latin America. Some items typical of Latin American cuisine include maize-based dishes arepas, empanadas, pupusas, tacos, tamales, tortillas and various salsas and other condiments (guacamole, pico de gallo, mole, chimichurri, chili, aji, pebre)."),
("Central Asian", "Central Asian cuisine has been influenced by Persian, Indian, Arab, Turkic, Chinese, and Mongol cultures, as well as the culinary traditions of other varied nomadic and sedentary civilizations. Common ingredients are nuts, fruis, grains, meat and vegetables."),
("East Asian", "East Asian cuisine includes Chinese, Hong Kong, Japanese, Korean, Macanese, Mongolian, Taiwanese, and Tibetan food. Ingredients common to many cultures in East Asia include rice, ginger, garlic, sesame seeds, chilis, dried onions, soy, and tofu."),
("African", "African cuisine is an integral part of the continent's diverse cultures reflecting its long and complex history. Common ingredients are vegetables, meat, grains, fruits and various spices.");
INSERT INTO posts_categories (post_id, category_id) VALUES
((SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), (SELECT id FROM categories WHERE title = "Drinks")),
((SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), (SELECT id FROM categories WHERE title = "Soft drinks")),
((SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), (SELECT id FROM categories WHERE title = "Drinks")),
((SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), (SELECT id FROM categories WHERE title = "Coffee")),
((SELECT id FROM posts WHERE title = "Why may sugar not caramelize?"), (SELECT id FROM categories WHERE title = "Sweet")),
((SELECT id FROM posts WHERE title = "Why may sugar not caramelize?"), (SELECT id FROM categories WHERE title = "Sugar confections")),
((SELECT id FROM posts WHERE title = "Some interesting ideas about nuggets"), (SELECT id FROM categories WHERE title = "Recipes")),
((SELECT id FROM posts WHERE title = "Some interesting ideas about nuggets"), (SELECT id FROM categories WHERE title = "Meat")),
((SELECT id FROM posts WHERE title = "Some interesting ideas about nuggets"), (SELECT id FROM categories WHERE title = "Frying")),
((SELECT id FROM posts WHERE title = "Some interesting ideas about nuggets"), (SELECT id FROM categories WHERE title = "Fast food")),
((SELECT id FROM posts WHERE title = "Is it possible to marinate bananas?"), (SELECT id FROM categories WHERE title = "Recipes")),
((SELECT id FROM posts WHERE title = "Is it possible to marinate bananas?"), (SELECT id FROM categories WHERE title = "Fruits")),
((SELECT id FROM posts WHERE title = "How to call popcorn in Coca-Cola syrup?"), (SELECT id FROM categories WHERE title = "Groats")),
((SELECT id FROM posts WHERE title = "How to call popcorn in Coca-Cola syrup?"), (SELECT id FROM categories WHERE title = "Sweet")),
((SELECT id FROM posts WHERE title = "About interesting cookies ideas"), (SELECT id FROM categories WHERE title = "Recipes")),
((SELECT id FROM posts WHERE title = "About interesting cookies ideas"), (SELECT id FROM categories WHERE title = "Sweet")),
((SELECT id FROM posts WHERE title = "About interesting cookies ideas"), (SELECT id FROM categories WHERE title = "Pastry")),
((SELECT id FROM posts WHERE title = "About interesting cookies ideas"), (SELECT id FROM categories WHERE title = "Baking")),
((SELECT id FROM posts WHERE title = "Why may the foam on the coffee not stick?"), (SELECT id FROM categories WHERE title = "Dairy products")),
((SELECT id FROM posts WHERE title = "Why may the foam on the coffee not stick?"), (SELECT id FROM categories WHERE title = "Drinks")),
((SELECT id FROM posts WHERE title = "Why may the foam on the coffee not stick?"), (SELECT id FROM categories WHERE title = "Hot drinks")),
((SELECT id FROM posts WHERE title = "Why may the foam on the coffee not stick?"), (SELECT id FROM categories WHERE title = "Coffee")),
((SELECT id FROM posts WHERE title = "Recipes from the past"), (SELECT id FROM categories WHERE title = "Recipes")),
((SELECT id FROM posts WHERE title = "What stock pot can I use for cooking cheese?"), (SELECT id FROM categories WHERE title = "Kitchenware"));
INSERT INTO preferences (user_id, category_id) VALUES
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM categories WHERE title = "Meat")),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM categories WHERE title = "Fruits")),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM categories WHERE title = "Frying")),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM categories WHERE title = "East Asian")),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM categories WHERE title = "Sweet")),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM categories WHERE title = "Sugar confections")),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM categories WHERE title = "French"));
INSERT INTO favorites (user_id, post_id) VALUES
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?")),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM posts WHERE title = "Why may sugar not caramelize?")),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM posts WHERE title = "About interesting cookies ideas")),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM posts WHERE title = "Why may the foam on the coffee not stick?")),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM posts WHERE title = "Is it possible to marinate bananas?")),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM posts WHERE title = "What stock pot can I use for cooking cheese?"));
INSERT INTO followings (user_id, post_id) VALUES
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?")),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?")),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?")),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM posts WHERE title = "How to call popcorn in Coca-Cola syrup?")),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM posts WHERE title = "About interesting cookies ideas")),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "About interesting cookies ideas")),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM posts WHERE title = "Why may the foam on the coffee not stick?"));
INSERT INTO followers (follower_id, followed_id) VALUES
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist")),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Tutturu")),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Superhacker_1905")),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist")),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Superhacker_1905")),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Tutturu")),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Kurigohan")),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Kurigohan")),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Kurigohan")),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist")),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Tutturu")),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Superhacker_1905")),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Shiny_finger")),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Shiny_finger")),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Shiny_finger")),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Shiny_finger")),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist")),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "Superhacker_1905")),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "Tutturu")),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "Kurigohan")),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Luka_Urushibara")),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Luka_Urushibara")),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Luka_Urushibara")),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Luka_Urushibara")),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "Luka_Urushibara")),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist")),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "Tutturu")),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "Superhacker_1905")),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "Kurigohan")),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "Shiny_finger")),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "FarisNyanNyan")),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Tutturu")),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "FarisNyanNyan")),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "FarisNyanNyan")),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "FarisNyanNyan")),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "FarisNyanNyan")),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "FarisNyanNyan")),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist")),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Superhacker_1905")),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Kurigohan")),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Shiny_finger")),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Luka_Urushibara")),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Superhacker_1905")),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "skyclad2010")),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "skyclad2010")),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "skyclad2010")),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "skyclad2010")),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "skyclad2010")),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "skyclad2010")),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "skyclad2010")),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist")),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Tutturu")),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Kurigohan")),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Shiny_finger")),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Luka_Urushibara")),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "FarisNyanNyan"));
INSERT INTO comments (author_id, content, post_id, comment_id, attachment) VALUES
((SELECT id FROM users WHERE login = "Tutturu"), "Tutturu-♪ Personally Mayushi thinks there's cherry in Dr Pepper.", (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, null),
((SELECT id FROM users WHERE login = "Superhacker_1905"), "Dr Pepper for sure has caffeine! Because why is it brown?", (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, null),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), "It's of course yes, but... There is also Cherry Dr Pepper, isn't it?", null, 1, null),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), "Fair. You know, caffeine is probably really the reason why Dr Pepper has a bit of brown sodas flavor. It is a very good idea.", null, 2, null),
((SELECT id FROM users WHERE login = "Tutturu"), "That's rigth, but what prevents Regular Dr Pepper from having a cherry flavor? So Cherry Dr Pepper just has a richer cherry flavor, right?", null, 3, null),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), "Hmmm... This also sounds good. You are right.", null, 5, null),
((SELECT id FROM users WHERE login = "Kurigohan"), "Isn't it too obvious? Of course I don't argue that Dr Pepper has cafeine, but personally I think that it's brown because of liquorice. And I think the liquorice is the reason why brown sodas have a taste similar to one of a cough mixture.", null, 2, null),
((SELECT id FROM users WHERE login = "Shiny_finger"), "I recently drank hibiscus tea with cherry and blackcurrant and it really tastes like Dr Pepper! O_O Maybe Dr Pepper really contains black currant... 🤔", (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, null),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), "I think it has a taste of almeownds or ameowretto. I can't taste any other flavors in Dr Pepper.", (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, null),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), "That may sound crazy, but I think Dr Pepper has the same taste as Tarkhuna...", (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, null),
((SELECT id FROM users WHERE login = "skyclad2010"), "I think Dr Pepper for sure has caramel, so the caramel can be the base of the syrup for home-made Dr Pepper!", (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, null),
((SELECT id FROM users WHERE login = "Kurigohan"), "Yes, it's possible to make espresso from instant coffee and it tastes like the one from ground coffee, but I think that espresso from ground coffee is more invigorating. Although it's up to you to decide whether to try such coffee or not.", (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, null),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), "It's nyacessary to have clean kitchenware so not only caramel, but other dishes will be cooked successfully!", (SELECT id FROM posts WHERE title = "Why may sugar not caramelize?"), null, null),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), "Try to add cytric acid to your caramel. At least it helps me, so I think this advice also can help you.", (SELECT id FROM posts WHERE title = "Why may sugar not caramelize?"), null, null),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), "First, the Organization sells you strange sugar and then, you can't make caramel. That is, check whether the sugar you use to make caramel is of good quality and, of course, don't trust the Organization.", (SELECT id FROM posts WHERE title = "Why may sugar not caramelize?"), null, null),
((SELECT id FROM users WHERE login = "Superhacker_1905"), "I saw one Georgian making nuggets from finely chopped chicken fillet and adding ginger, garlic, soy sauce, peppers and starch diluted in milk. I think it will be very tasty.", (SELECT id FROM posts WHERE title = "Some interesting ideas about nuggets"), null, null),
((SELECT id FROM users WHERE login = "Tutturu"), "Wow, Mayushi is already interested! It for sure must be tasted! In addition, such nuggets must taste like karaage! ( ☆∀☆)", null, 16, null),
((SELECT id FROM users WHERE login = "Superhacker_1905"), "I think that in theory, bananas can be marinated, but maybe they will become soft...", (SELECT id FROM posts WHERE title = "Is it possible to marinate bananas?"), null, null),
((SELECT id FROM users WHERE login = "skyclad2010"), "If you don't marinate bananas for too long, they won't turn into slugs, so everything is possible!", null, 18, null),
((SELECT id FROM users WHERE login = "Shiny_finger"), "I saw one recipe where peeled bananas were dipped in red orange juice with spices and a bit of lemon juice. It looks tasty, so you can try! ❤️", (SELECT id FROM posts WHERE title = "Is it possible to marinate bananas?"), null, null),
((SELECT id FROM users WHERE login = "skyclad2010"), "I think pop-cola sounds cooler!", (SELECT id FROM posts WHERE title = "How to call popcorn in Coca-Cola syrup?"), null, null),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), "I think coca-corn suits more. The main in this name is corn, isn't it?", (SELECT id FROM posts WHERE title = "How to call popcorn in Coca-Cola syrup?"), null, null),
((SELECT id FROM users WHERE login = "Kurigohan"), "It depends on which ingredient was present in greater quality. If there is more corn, the name should be coca-corn, and vice versa.", (SELECT id FROM posts WHERE title = "How to call popcorn in Coca-Cola syrup?"), null, null),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), "You may try to cook cookies from a meat grinder. Simple shortbread and not from electric, but manual meat grinder.", (SELECT id FROM posts WHERE title = "About interesting cookies ideas"), null, null),
((SELECT id FROM users WHERE login = "Tutturu"), "Tutturu-♪ Try to make oatcakes, you for sure will be delighted! ( ＾ω＾)", (SELECT id FROM posts WHERE title = "About interesting cookies ideas"), null, null),
((SELECT id FROM users WHERE login = "Tutturu"), "Tutturu-♪ As Mayushi remembers, the foam stays on top when it's made from ultra-pasteurized milk. Home boiled milk isn't suitable for the foam.", (SELECT id FROM posts WHERE title = "Why may the foam on the coffee not stick?"), null, null),
((SELECT id FROM users WHERE login = "Tutturu"), "Tutturu-♪ Mayushi is ready to share the recipe of Chicken Kiev from 1915! Take 400 g of meat, mince it three times, then add one raw egg, 3 tablespoons of butter, 70-75 g of a loaf of bread soaked in milk and squeezed well, salt, and mix thoroughly. Form the patties as follows: take approximately one tablespoon of meat per patty, form a flatbread, then place a piece of butter in the center and fold the edges of the patty with a knife so that the piece of butter is inside. For the breading, beat one egg, dip the patties in it, and then roll them in breadcrumbs. Fry the patties in the butter, and once golden brown, remove them.", (SELECT id FROM posts WHERE title = "Recipes from the past"), null, null),
((SELECT id FROM users WHERE login = "Kurigohan"), "Double-bottomed stock pots are very good for cheeses because milk will cool slowlier. Enameled or stainless steel pots are suitable. You can buy a 12-liter stock pot so you can cook one kilogram of cheese, but look at the price and choose a volume suitable for you.", (SELECT id FROM posts WHERE title = "What stock pot can I use for cooking cheese?"), null, null);
INSERT INTO likes (author_id, post_id, comment_id, type) VALUES
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "like"),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "like"),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "like"),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Personally Mayushi thinks there's cherry in Dr Pepper."), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Personally Mayushi thinks there's cherry in Dr Pepper."), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "Dr Pepper for sure has caffeine! Because why is it brown?"), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "Dr Pepper for sure has caffeine! Because why is it brown?"), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "Dr Pepper for sure has caffeine! Because why is it brown?"), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "It's of course yes, but... There is also Cherry Dr Pepper, isn't it?"), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "It's of course yes, but... There is also Cherry Dr Pepper, isn't it?"), "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), null, (SELECT id FROM comments WHERE content = "Fair. You know, caffeine is probably really the reason why Dr Pepper has a bit of brown sodas flavor. It is a very good idea."), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "That's rigth, but what prevents Regular Dr Pepper from having a cherry flavor? So Cherry Dr Pepper just has a richer cherry flavor, right?"), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "Hmmm... This also sounds good. You are right."), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "Isn't it too obvious? Of course I don't argue that Dr Pepper has cafeine, but personally I think that it's brown because of liquorice. And I think the liquorice is the reason why brown sodas have a taste similar to one of a cough mixture."), "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), null, (SELECT id FROM comments WHERE content = "Isn't it too obvious? Of course I don't argue that Dr Pepper has cafeine, but personally I think that it's brown because of liquorice. And I think the liquorice is the reason why brown sodas have a taste similar to one of a cough mixture."), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "I recently drank hibiscus tea with cherry and blackcurrant and it really tastes like Dr Pepper! O_O Maybe Dr Pepper really contains black currant... 🤔"), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "I think it has a taste of almeownds or ameowretto. I can't taste any other flavors in Dr Pepper."), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "That may sound crazy, but I think Dr Pepper has the same taste as Tarkhuna..."), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "I think Dr Pepper for sure has caramel, so the caramel can be the base of the syrup for home-made Dr Pepper!"), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "Yes, it's possible to make espresso from instant coffee and it tastes like the one from ground coffee, but I think that espresso from ground coffee is more invigorating. Although it's up to you to decide whether to try such coffee or not."), "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), null, (SELECT id FROM comments WHERE content = "Yes, it's possible to make espresso from instant coffee and it tastes like the one from ground coffee, but I think that espresso from ground coffee is more invigorating. Although it's up to you to decide whether to try such coffee or not."), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM posts WHERE title = "Why may sugar not caramelize?"), null, "like"),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM posts WHERE title = "Why may sugar not caramelize?"), null, "like"),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM posts WHERE title = "Why may sugar not caramelize?"), null, "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM posts WHERE title = "Some interesting ideas about nuggets"), null, "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM posts WHERE title = "Some interesting ideas about nuggets"), null, "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Some interesting ideas about nuggets"), null, "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Is it possible to marinate bananas?"), null, "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM posts WHERE title = "Is it possible to marinate bananas?"), null, "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM posts WHERE title = "Is it possible to marinate bananas?"), null, "like"),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM posts WHERE title = "Is it possible to marinate bananas?"), null, "like"),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM posts WHERE title = "Is it possible to marinate bananas?"), null, "like"),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM posts WHERE title = "Is it possible to marinate bananas?"), null, "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM posts WHERE title = "Is it possible to marinate bananas?"), null, "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM posts WHERE title = "How to call popcorn in Coca-Cola syrup?"), null, "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM posts WHERE title = "How to call popcorn in Coca-Cola syrup?"), null, "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "How to call popcorn in Coca-Cola syrup?"), null, "like"),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM posts WHERE title = "How to call popcorn in Coca-Cola syrup?"), null, "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "About interesting cookies ideas"), null, "like"),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM posts WHERE title = "About interesting cookies ideas"), null, "like"),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM posts WHERE title = "About interesting cookies ideas"), null, "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM posts WHERE title = "Why may the foam on the coffee not stick?"), null, "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Why may the foam on the coffee not stick?"), null, "like"),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM posts WHERE title = "Why may the foam on the coffee not stick?"), null, "like"),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM posts WHERE title = "Why may the foam on the coffee not stick?"), null, "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM posts WHERE title = "Recipes from the past"), null, "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Recipes from the past"), null, "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM posts WHERE title = "Recipes from the past"), null, "like"),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM posts WHERE title = "Recipes from the past"), null, "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM posts WHERE title = "What stock pot can I use for cooking cheese?"), null, "like"),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM posts WHERE title = "What stock pot can I use for cooking cheese?"), null, "like"),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM posts WHERE title = "What stock pot can I use for cooking cheese?"), null, "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "It's nyacessary to have clean kitchenware so not only caramel, but other dishes will be cooked successfully!"), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "It's nyacessary to have clean kitchenware so not only caramel, but other dishes will be cooked successfully!"), "like"),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), null, (SELECT id FROM comments WHERE content = "It's nyacessary to have clean kitchenware so not only caramel, but other dishes will be cooked successfully!"), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "Try to add cytric acid to your caramel. At least it helps me, so I think this advice also can help you."), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "Try to add cytric acid to your caramel. At least it helps me, so I think this advice also can help you."), "like"),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), null, (SELECT id FROM comments WHERE content = "Try to add cytric acid to your caramel. At least it helps me, so I think this advice also can help you."), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "First, the Organization sells you strange sugar and then, you can't make caramel. That is, check whether the sugar you use to make caramel is of good quality and, of course, don't trust the Organization."), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "First, the Organization sells you strange sugar and then, you can't make caramel. That is, check whether the sugar you use to make caramel is of good quality and, of course, don't trust the Organization."), "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), null, (SELECT id FROM comments WHERE content = "I saw one Georgian making nuggets from finely chopped chicken fillet and adding ginger, garlic, soy sauce, peppers and starch diluted in milk. I think it will be very tasty."), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "I saw one Georgian making nuggets from finely chopped chicken fillet and adding ginger, garlic, soy sauce, peppers and starch diluted in milk. I think it will be very tasty."), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "I saw one Georgian making nuggets from finely chopped chicken fillet and adding ginger, garlic, soy sauce, peppers and starch diluted in milk. I think it will be very tasty."), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "I saw one Georgian making nuggets from finely chopped chicken fillet and adding ginger, garlic, soy sauce, peppers and starch diluted in milk. I think it will be very tasty."), "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), null, (SELECT id FROM comments WHERE content = "Wow, Mayushi is already interested! It for sure must be tasted! In addition, such nuggets must taste like karaage! ( ☆∀☆)"), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "Wow, Mayushi is already interested! It for sure must be tasted! In addition, such nuggets must taste like karaage! ( ☆∀☆)"), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "Wow, Mayushi is already interested! It for sure must be tasted! In addition, such nuggets must taste like karaage! ( ☆∀☆)"), "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), null, (SELECT id FROM comments WHERE content = "Wow, Mayushi is already interested! It for sure must be tasted! In addition, such nuggets must taste like karaage! ( ☆∀☆)"), "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), null, (SELECT id FROM comments WHERE content = "I think that in theory, bananas can be marinated, but maybe they will become soft..."), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "I think that in theory, bananas can be marinated, but maybe they will become soft..."), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "I think that in theory, bananas can be marinated, but maybe they will become soft..."), "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), null, (SELECT id FROM comments WHERE content = "If you don't marinate bananas for too long, they won't turn into slugs, so everything is possible!"), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "If you don't marinate bananas for too long, they won't turn into slugs, so everything is possible!"), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "If you don't marinate bananas for too long, they won't turn into slugs, so everything is possible!"), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "I saw one recipe where peeled bananas were dipped in red orange juice with spices and a bit of lemon juice. It looks tasty, so you can try! ❤️"), "like"),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), null, (SELECT id FROM comments WHERE content = "I saw one recipe where peeled bananas were dipped in red orange juice with spices and a bit of lemon juice. It looks tasty, so you can try! ❤️"), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "I saw one recipe where peeled bananas were dipped in red orange juice with spices and a bit of lemon juice. It looks tasty, so you can try! ❤️"), "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), null, (SELECT id FROM comments WHERE content = "I saw one recipe where peeled bananas were dipped in red orange juice with spices and a bit of lemon juice. It looks tasty, so you can try! ❤️"), "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), null, (SELECT id FROM comments WHERE content = "I think pop-cola sounds cooler!"), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "I think pop-cola sounds cooler!"), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "I think pop-cola sounds cooler!"), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "I think pop-cola sounds cooler!"), "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), null, (SELECT id FROM comments WHERE content = "I think coca-corn suits more. The main in this name is corn, isn't it?"), "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), null, (SELECT id FROM comments WHERE content = "I think coca-corn suits more. The main in this name is corn, isn't it?"), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "I think coca-corn suits more. The main in this name is corn, isn't it?"), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "I think coca-corn suits more. The main in this name is corn, isn't it?"), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "I think coca-corn suits more. The main in this name is corn, isn't it?"), "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), null, (SELECT id FROM comments WHERE content = "It depends on which ingredient was present in greater quality. If there is more corn, the name should be coca-corn, and vice versa."), "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), null, (SELECT id FROM comments WHERE content = "It depends on which ingredient was present in greater quality. If there is more corn, the name should be coca-corn, and vice versa."), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "It depends on which ingredient was present in greater quality. If there is more corn, the name should be coca-corn, and vice versa."), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "It depends on which ingredient was present in greater quality. If there is more corn, the name should be coca-corn, and vice versa."), "like"),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), null, (SELECT id FROM comments WHERE content = "You may try to cook cookies from a meat grinder. Simple shortbread and not from electric, but manual meat grinder."), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "You may try to cook cookies from a meat grinder. Simple shortbread and not from electric, but manual meat grinder."), "like"),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), null, (SELECT id FROM comments WHERE content = "You may try to cook cookies from a meat grinder. Simple shortbread and not from electric, but manual meat grinder."), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "You may try to cook cookies from a meat grinder. Simple shortbread and not from electric, but manual meat grinder."), "like"),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Try to make oatcakes, you for sure will be delighted! ( ＾ω＾)"), "like"),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Try to make oatcakes, you for sure will be delighted! ( ＾ω＾)"), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Try to make oatcakes, you for sure will be delighted! ( ＾ω＾)"), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Try to make oatcakes, you for sure will be delighted! ( ＾ω＾)"), "like"),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ As Mayushi remembers, the foam stays on top when it's made from ultra-pasteurized milk. Home boiled milk isn't suitable for the foam."), "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ As Mayushi remembers, the foam stays on top when it's made from ultra-pasteurized milk. Home boiled milk isn't suitable for the foam."), "like"),
((SELECT id FROM users WHERE login = "Shiny_finger"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ As Mayushi remembers, the foam stays on top when it's made from ultra-pasteurized milk. Home boiled milk isn't suitable for the foam."), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ As Mayushi remembers, the foam stays on top when it's made from ultra-pasteurized milk. Home boiled milk isn't suitable for the foam."), "like"),
((SELECT id FROM users WHERE login = "skyclad2010"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Mayushi is ready to share the recipe of Chicken Kiev from 1915! Take 400 g of meat, mince it three times, then add one raw egg, 3 tablespoons of butter, 70-75 g of a loaf of bread soaked in milk and squeezed well, salt, and mix thoroughly. Form the patties as follows: take approximately one tablespoon of meat per patty, form a flatbread, then place a piece of butter in the center and fold the edges of the patty with a knife so that the piece of butter is inside. For the breading, beat one egg, dip the patties in it, and then roll them in breadcrumbs. Fry the patties in the butter, and once golden brown, remove them."), "like"),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Mayushi is ready to share the recipe of Chicken Kiev from 1915! Take 400 g of meat, mince it three times, then add one raw egg, 3 tablespoons of butter, 70-75 g of a loaf of bread soaked in milk and squeezed well, salt, and mix thoroughly. Form the patties as follows: take approximately one tablespoon of meat per patty, form a flatbread, then place a piece of butter in the center and fold the edges of the patty with a knife so that the piece of butter is inside. For the breading, beat one egg, dip the patties in it, and then roll them in breadcrumbs. Fry the patties in the butter, and once golden brown, remove them."), "like"),
((SELECT id FROM users WHERE login = "Superhacker_1905"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Mayushi is ready to share the recipe of Chicken Kiev from 1915! Take 400 g of meat, mince it three times, then add one raw egg, 3 tablespoons of butter, 70-75 g of a loaf of bread soaked in milk and squeezed well, salt, and mix thoroughly. Form the patties as follows: take approximately one tablespoon of meat per patty, form a flatbread, then place a piece of butter in the center and fold the edges of the patty with a knife so that the piece of butter is inside. For the breading, beat one egg, dip the patties in it, and then roll them in breadcrumbs. Fry the patties in the butter, and once golden brown, remove them."), "like"),
((SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Mayushi is ready to share the recipe of Chicken Kiev from 1915! Take 400 g of meat, mince it three times, then add one raw egg, 3 tablespoons of butter, 70-75 g of a loaf of bread soaked in milk and squeezed well, salt, and mix thoroughly. Form the patties as follows: take approximately one tablespoon of meat per patty, form a flatbread, then place a piece of butter in the center and fold the edges of the patty with a knife so that the piece of butter is inside. For the breading, beat one egg, dip the patties in it, and then roll them in breadcrumbs. Fry the patties in the butter, and once golden brown, remove them."), "like"),
((SELECT id FROM users WHERE login = "Shiny_finger"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Mayushi is ready to share the recipe of Chicken Kiev from 1915! Take 400 g of meat, mince it three times, then add one raw egg, 3 tablespoons of butter, 70-75 g of a loaf of bread soaked in milk and squeezed well, salt, and mix thoroughly. Form the patties as follows: take approximately one tablespoon of meat per patty, form a flatbread, then place a piece of butter in the center and fold the edges of the patty with a knife so that the piece of butter is inside. For the breading, beat one egg, dip the patties in it, and then roll them in breadcrumbs. Fry the patties in the butter, and once golden brown, remove them."), "like"),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Mayushi is ready to share the recipe of Chicken Kiev from 1915! Take 400 g of meat, mince it three times, then add one raw egg, 3 tablespoons of butter, 70-75 g of a loaf of bread soaked in milk and squeezed well, salt, and mix thoroughly. Form the patties as follows: take approximately one tablespoon of meat per patty, form a flatbread, then place a piece of butter in the center and fold the edges of the patty with a knife so that the piece of butter is inside. For the breading, beat one egg, dip the patties in it, and then roll them in breadcrumbs. Fry the patties in the butter, and once golden brown, remove them."), "like"),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Mayushi is ready to share the recipe of Chicken Kiev from 1915! Take 400 g of meat, mince it three times, then add one raw egg, 3 tablespoons of butter, 70-75 g of a loaf of bread soaked in milk and squeezed well, salt, and mix thoroughly. Form the patties as follows: take approximately one tablespoon of meat per patty, form a flatbread, then place a piece of butter in the center and fold the edges of the patty with a knife so that the piece of butter is inside. For the breading, beat one egg, dip the patties in it, and then roll them in breadcrumbs. Fry the patties in the butter, and once golden brown, remove them."), "like"),
((SELECT id FROM users WHERE login = "Shiny_finger"), null, (SELECT id FROM comments WHERE content = "Double-bottomed stock pots are very good for cheeses because milk will cool slowlier. Enameled or stainless steel pots are suitable. You can buy a 12-liter stock pot so you can cook one kilogram of cheese, but look at the price and choose a volume suitable for you."), "like"),
((SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "Double-bottomed stock pots are very good for cheeses because milk will cool slowlier. Enameled or stainless steel pots are suitable. You can buy a 12-liter stock pot so you can cook one kilogram of cheese, but look at the price and choose a volume suitable for you."), "like"),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), null, (SELECT id FROM comments WHERE content = "Double-bottomed stock pots are very good for cheeses because milk will cool slowlier. Enameled or stainless steel pots are suitable. You can buy a 12-liter stock pot so you can cook one kilogram of cheese, but look at the price and choose a volume suitable for you."), "like"),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), null, (SELECT id FROM comments WHERE content = "Double-bottomed stock pots are very good for cheeses because milk will cool slowlier. Enameled or stainless steel pots are suitable. You can buy a 12-liter stock pot so you can cook one kilogram of cheese, but look at the price and choose a volume suitable for you."), "like");
INSERT INTO notifications (addressee_id, figurant_id, post_id, comment_id, sense, is_read) VALUES
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Tutturu"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Superhacker_1905"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Tutturu"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Superhacker_1905"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Superhacker_1905"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Tutturu"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Kurigohan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Kurigohan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Kurigohan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "Tutturu"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "Superhacker_1905"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "Kurigohan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Shiny_finger"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Shiny_finger"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Shiny_finger"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Shiny_finger"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "Tutturu"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "Superhacker_1905"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "Kurigohan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "Shiny_finger"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Luka_Urushibara"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Luka_Urushibara"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Luka_Urushibara"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Luka_Urushibara"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "Luka_Urushibara"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Tutturu"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "FarisNyanNyan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Superhacker_1905"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Kurigohan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Shiny_finger"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Luka_Urushibara"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "FarisNyanNyan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "FarisNyanNyan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "FarisNyanNyan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "FarisNyanNyan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "FarisNyanNyan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "skyclad2010"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Tutturu"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Superhacker_1905"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Kurigohan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Shiny_finger"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Luka_Urushibara"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "FarisNyanNyan"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "skyclad2010"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "skyclad2010"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "skyclad2010"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "skyclad2010"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "skyclad2010"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "skyclad2010"), null, null, "is following you!", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "is following your post:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Personally Mayushi thinks there's cherry in Dr Pepper."), "commented on you:", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Personally Mayushi thinks there's cherry in Dr Pepper."), "commented on the post you are following:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Superhacker_1905"), null, (SELECT id FROM comments WHERE content = "Dr Pepper for sure has caffeine! Because why is it brown?"), "commented on you:", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id from comments WHERE content = "It's of course yes, but... There is also Cherry Dr Pepper, isn't it?"), "commented on you:", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "It's of course yes, but... There is also Cherry Dr Pepper, isn't it?"), "commented on the post you are following:", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id from comments WHERE content = "Fair. You know, caffeine is probably really the reason why Dr Pepper has a bit of brown sodas flavor. It is a very good idea."), "commented on you:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "That's rigth, but what prevents Regular Dr Pepper from having a cherry flavor? So Cherry Dr Pepper just has a richer cherry flavor, right?"), "commented on you:", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "That's rigth, but what prevents Regular Dr Pepper from having a cherry flavor? So Cherry Dr Pepper just has a richer cherry flavor, right?"), "commented on the post you are following:", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id from comments WHERE content = "Hmmm... This also sounds good. You are right."), "commented on you:", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id from comments WHERE content = "Hmmm... This also sounds good. You are right."), "commented on the post you are following:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "reacted to your post:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM posts WHERE title = "What is Dr Pepper made of?"), null, "reacted to your post:", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Superhacker_1905"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Personally Mayushi thinks there's cherry in Dr Pepper."), "reacted to your comment:", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "Tutturu-♪ Personally Mayushi thinks there's cherry in Dr Pepper."), "reacted to your comment:", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "Dr Pepper for sure has caffeine! Because why is it brown?"), "reacted to your comment:", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "Dr Pepper for sure has caffeine! Because why is it brown?"), "reacted to your comment:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Superhacker_1905"), null, (SELECT id FROM comments WHERE content = "Fair. You know, caffeine is probably really the reason why Dr Pepper has a bit of brown sodas flavor. It is a very good idea."), "reacted to your comment:", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "That's rigth, but what prevents Regular Dr Pepper from having a cherry flavor? So Cherry Dr Pepper just has a richer cherry flavor, right?"), "reacted to your comment:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Tutturu"), null, (SELECT id FROM comments WHERE content = "Hmmm... This also sounds good. You are right."), "reacted to your comment:", 1),
((SELECT id FROM users WHERE login = "Tutturu"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "Superhacker_1905"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "Shiny_finger"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "Luka_Urushibara"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "FarisNyanNyan"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "published a post:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "reacted to your post:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "is following your post:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "reacted to your post:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "is following your post:", 1),
((SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "Yes, it's possible to make espresso from instant coffee and it tastes like the one from ground coffee, but I think that espresso from ground coffee is more invigorating. Although it's up to you to decide whether to try such coffee or not."), "commented on you:", 1),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Kurigohan"), null, (SELECT id FROM comments WHERE content = "Yes, it's possible to make espresso from instant coffee and it tastes like the one from ground coffee, but I think that espresso from ground coffee is more invigorating. Although it's up to you to decide whether to try such coffee or not."), "commented on the post you are following:", 1),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), null, (SELECT id FROM comments WHERE content = "Yes, it's possible to make espresso from instant coffee and it tastes like the one from ground coffee, but I think that espresso from ground coffee is more invigorating. Although it's up to you to decide whether to try such coffee or not."), "reacted to your comment:", 1),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "skyclad2010"), null, (SELECT id FROM comments WHERE content = "Yes, it's possible to make espresso from instant coffee and it tastes like the one from ground coffee, but I think that espresso from ground coffee is more invigorating. Although it's up to you to decide whether to try such coffee or not."), "reacted to your comment:", 1),
((SELECT id FROM users WHERE login = "Kurigohan"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "locked the post:", 1),
((SELECT id FROM users WHERE login = "skyclad2010"), (SELECT id FROM users WHERE login = "Kyouki_no_mad_scientist"), (SELECT id FROM posts WHERE title = "Espresso from instant coffee: is it real?"), null, "locked the post:", 1);

